#-------------------------------
# General Site Settings

title: Alpha Sierra
description: A Web Blog maintained by Anubhav Sharma
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.anubhav-sharma.com/" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Anubhav Sharma
author-avatar: Profile.jpeg


#-------------------------------
# Contact links
facebook:  https://www.facebook.com/profile.php?id=100026291986159/ # Add your Facebook handle
twitter:   https://twitter.com/Anubhav88336338/ # Add your Facebook handle
instagram: https://www.instagram.com/anubhav_sharma9/ # Add your Facebook handle
pinterest: https://www.pinterest.com/ # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: jekyll-blog-5 # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: G-F5YP8XXRJH # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
